import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,mkdir,symlink} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {prepareEvidence} from '../src/evidence-workflow.mjs';
async function fixture(){const root=await mkdtemp(path.join(os.tmpdir(),'jev-workflow-test-'));await writeFile(path.join(root,'a.txt'),'Inventory panel is stale.\nNo restart test evidence.');await writeFile(path.join(root,'b.txt'),'Unrelated art description.');return {root,receiptRoot:path.join(root,'receipts')};}
function reply(request,{values={},checks={},labels={},action='auto',complete=true}={}){return {model:'jev-1.13.0',action,truncated:false,coverage:{complete},usage:{input_tokens:1,output_tokens:1},answers:Object.fromEntries(Object.entries(request.questions).map(([k,q])=>{
 if(q.type==='noul')return [k,{type:'noul',noul:values[k]??(k.startsWith('relevant')?.99:.01)}];
 const options=Object.keys(q.criteria);const chosen=k.startsWith('check_')?(checks[k]??'supported'):(labels[k]??options[0]);return [k,{type:'choice',choice:chosen,confidence:1,probabilities:Object.fromEntries(options.map(o=>[o,o===chosen?1:0]))}];
}))};}
function input(f){return {task:'Collect inventory issue evidence',root:f.root,sources:[{id:'a',path:'a.txt'},{id:'b',path:'b.txt'}]};}
function opts(f,evaluate){return {...f,allowedRoots:[f.root],evaluate};}
test('one inference collects, filters and writes exact evidence plus full receipt',async()=>{const f=await fixture();let calls=0;const r=await prepareEvidence(input(f),opts(f,async req=>{calls++;return reply(req,{values:{relevant_b:.01}});}));assert.equal(calls,1);assert.equal(r.status,'EVIDENCE_READY');assert.deepEqual(r.evidence.map(e=>e.id),['a']);const receipt=JSON.parse(await readFile(r.receipt_path,'utf8'));assert.equal(receipt.request.state.evidence.length,2);assert.equal(r.evidence[0].text,await readFile(path.join(f.root,'a.txt'),'utf8'));});
test('counterevidence and uncertain sources survive relevance filtering',async()=>{const f=await fixture();const r=await prepareEvidence(input(f),opts(f,async req=>reply(req,{action:'review',values:{relevant_a:.01,counter_a:.99,relevant_b:.2,counter_b:.01}})));assert.equal(r.status,'REVIEW_REQUIRED');assert.equal(r.evidence.length,2);});
test('claim-linked evidence survives filtering; unsupported stays review',async()=>{const f=await fixture();const i=input(f);i.checks=[{id:'run',claim:'Reload test passed',evidence_ids:['b']}];const r=await prepareEvidence(i,opts(f,async req=>reply(req,{values:{relevant_b:.01},checks:{check_run:'unsupported'}})));assert.equal(r.evidence.length,2);assert.equal(r.status,'REVIEW_REQUIRED');assert.equal(r.checks[0].verdict,'unsupported');});
test('pinned source retained and log labels returned',async()=>{const f=await fixture();const i=input(f);i.sources[1].pinned=true;i.labels=[{id:'bug',description:'Bug reports'},{id:'art',description:'Art notes'}];const r=await prepareEvidence(i,opts(f,async req=>reply(req,{values:{relevant_b:.01},labels:{label_a:'bug',label_b:'art'}})));assert.equal(r.evidence.length,2);assert.equal(r.selections[1].label.value,'art');});
test('file modification during inference makes the entire result stale',async()=>{const f=await fixture();const r=await prepareEvidence(input(f),opts(f,async req=>{await writeFile(path.join(f.root,'a.txt'),'Concurrent change');return reply(req);}));assert.equal(r.status,'STALE_SOURCE');assert.deepEqual(r.stale_sources,['a']);});
test('invalid ranges, traversal, credentials and unknown references never reach inference',async()=>{const f=await fixture();let calls=0;const o=opts(f,async req=>{calls++;return reply(req);});for(const change of [i=>i.sources[0].path='../escape.txt',i=>i.sources[0].path='.env',i=>{i.sources[0].start_line=1;i.sources[0].end_line=999;},i=>i.checks=[{id:'x',claim:'x',evidence_ids:['missing']}],i=>i.root=path.dirname(f.root)]){const i=input(f);change(i);await assert.rejects(prepareEvidence(i,o));}await writeFile(path.join(f.root,'a.txt'),'Authorization: Bearer '+ 'exampleSensitiveToken123456789');await assert.rejects(prepareEvidence(input(f),o),/SENSITIVE_INPUT/);assert.equal(calls,0);});
test('question/character budgets reject without truncation or inference',async()=>{const f=await fixture();let calls=0;const o=opts(f,async req=>{calls++;return reply(req);});const i=input(f);i.sources=Array.from({length:10},(_,n)=>({id:'f'+n,path:'a.txt'}));i.labels=[{id:'bug',description:'Bug'},{id:'art',description:'Art'}];await assert.rejects(prepareEvidence(i,o),/QUESTION_LIMIT/);await writeFile(path.join(f.root,'a.txt'),'x'.repeat(25000));await assert.rejects(prepareEvidence(input(f),o),/INPUT_CHARACTER_LIMIT/);assert.equal(calls,0);});

test('pinned collection alone needs zero model calls; linked checks ask only useful questions',async()=>{const f=await fixture();const i=input(f);i.sources.forEach(s=>s.pinned=true);let calls=0;const o=opts(f,async req=>{calls++;assert.deepEqual(Object.keys(req.questions),['check_x']);return reply(req);});const r=await prepareEvidence(i,o);assert.equal(calls,0);assert.equal(r.metrics.workflow_inference_calls,0);i.checks=[{id:'x',claim:'Inventory panel is stale',evidence_ids:['a']}];const checked=await prepareEvidence(i,o);assert.equal(calls,1);assert.equal(checked.metrics.question_count,1);assert.equal(checked.status,'EVIDENCE_READY');});
test('malformed, incomplete, wrong model and API failures cannot return ready',async()=>{const f=await fixture();for(const change of [r=>r.coverage.complete=false,r=>r.answers.relevant_a.noul=NaN,r=>delete r.answers.counter_a,r=>r.model='mock'])await assert.rejects(prepareEvidence(input(f),opts(f,async req=>{const r=reply(req);change(r);return r;})));await assert.rejects(prepareEvidence(input(f),opts(f,async()=>{throw Error('fixture transport failure');})));});
test('full GDScript symbol extraction and source hash are reproducible',async()=>{const f=await fixture();await writeFile(path.join(f.root,'a.gd'),'extends RefCounted\nfunc target():\n\treturn 1\n\nfunc other():\n\treturn 2\n');const i=input(f);i.sources=[{id:'code',path:'a.gd',symbol:'target'}];const r=await prepareEvidence(i,opts(f,async req=>reply(req)));assert.equal(r.evidence[0].start_line,2);assert.ok(!r.evidence[0].text.includes('other'));assert.match(r.evidence[0].file_sha256,/^[a-f0-9]{64}$/);});
test('cancelled call performs no inference',async()=>{const f=await fixture();const c=new AbortController();c.abort();let calls=0;await assert.rejects(prepareEvidence(input(f),{...opts(f,async req=>{calls++;return reply(req);}),signal:c.signal}),/CANCELLED/);assert.equal(calls,0);});
test('junction traversal outside approved root is rejected',async()=>{const f=await fixture();const outside=await fixture();await symlink(outside.root,path.join(f.root,'alias'),'junction');const i=input(f);i.sources=[{id:'a',path:'alias/a.txt'}];let calls=0;await assert.rejects(prepareEvidence(i,opts(f,async req=>{calls++;return reply(req);})),/PATH_ESCAPES_ROOT/);assert.equal(calls,0);});

test('explicit Lua and Luau line ranges work without a model call',async()=>{
 const f=await fixture();for(const ext of ['lua','luau']){await writeFile(path.join(f.root,'code.'+ext),'-- long module\nreturn true\n');const i={...input(f),sources:[{id:'code',path:'code.'+ext,start_line:2,end_line:2,pinned:true}]};const r=await prepareEvidence(i,opts(f,()=>assert.fail('No inference')));assert.equal(r.evidence[0].text,'return true');assert.equal(r.metrics.workflow_inference_calls,0);}
});
