import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,realpath,rm,symlink} from 'node:fs/promises';
import path from 'node:path';
import {tmpdir} from 'node:os';
import {prepareBrief,excerpt} from '../src/pijev-bridge.mjs';
async function setup(t){
 const root=await mkdtemp(path.join(tmpdir(),'pijev-bridge-')),canonical=await realpath(root),parent=await realpath(tmpdir());
 t.after(async()=>{const resolved=await realpath(root);assert.equal(resolved,canonical);assert.equal(path.dirname(resolved),parent);assert.ok(path.basename(resolved).startsWith('pijev-bridge-'));await rm(resolved,{recursive:true});});
 await mkdir(path.join(root,'src'));await writeFile(path.join(root,'src','ttl.ts'),'export function stale(deadline, now) { return now > deadline; }\n');
 await writeFile(path.join(root,'src','paint.ts'),'export function tint() { return "blue"; }\n');
 const input={root,path:'src',query:'Find expiration deadline handling',glob:'*.ts',max_candidates:4};
 return {root,input,options:{roots:[root],runs:path.join(root,'receipts')}};
}
const evaluate=async input=>({model:'jev-1.13.0',coverage:{complete:true},truncated:false,answers:Object.fromEntries(Object.keys(input.questions).map(id=>[id,{type:'noul',noul:input.state.candidates[id].path==='ttl.ts'?.99:.1}])),usage:{input_tokens:1,output_tokens:1}});
test('actual upstream discovery and ranking produce a source-hashed brief',async t=>{const f=await setup(t);const result=await prepareBrief(f.input,{...f.options,evaluate});assert.equal(result.status,'BRIEF_READY');assert.equal(result.evidence[0].path,'ttl.ts');assert.equal(result.metrics.calls,1);assert.equal(result.evidence.length,2);assert.equal(result.evidence[0].kind,'whole_file');assert.equal(result.coverage.repository_complete,false);assert.ok(JSON.parse(await readFile(result.receipt_path,'utf8')).receipts[0].input_sha256);});
test('uncertain ranking preserves candidates rather than approving',async t=>{const f=await setup(t);const result=await prepareBrief(f.input,{...f.options,evaluate:async i=>{const r=await evaluate(i);for(const a of Object.values(r.answers))a.noul=.5;return r;}});assert.equal(result.status,'REVIEW_REQUIRED');assert.equal(result.evidence.length,2);});
test('partial response and concurrent edit invalidate the brief',async t=>{const f=await setup(t);await assert.rejects(()=>prepareBrief(f.input,{...f.options,evaluate:async i=>({...await evaluate(i),truncated:true})}),/INVALID_RESPONSE/);await assert.rejects(()=>prepareBrief(f.input,{...f.options,evaluate:async i=>{await writeFile(path.join(f.root,'src','ttl.ts'),'export function stale() { return false; }');return evaluate(i);}}),/STALE_SOURCE/);});
test('rejects broad, traversal, sensitive and junction scopes',async t=>{const f=await setup(t);for(const p of ['.','../','src/../src','secrets'])await assert.rejects(()=>prepareBrief({...f.input,path:p},{...f.options,evaluate}),/INVALID_OR_SENSITIVE_SCOPE/);await symlink(path.join(f.root,'src'),path.join(f.root,'alias'),'junction');await assert.rejects(()=>prepareBrief({...f.input,path:'alias'},{...f.options,evaluate}),/SCOPE_ESCAPE/);});
test('source credential and aborted call make no inference',async t=>{const f=await setup(t);await writeFile(path.join(f.root,'src','ttl.ts'),'// apikey_'+'x'.repeat(35));await assert.rejects(()=>prepareBrief(f.input,{...f.options,evaluate:()=>assert.fail('No inference')}),/SENSITIVE_SOURCE/);const controller=new AbortController();controller.abort();await assert.rejects(()=>prepareBrief(f.input,{...f.options,signal:controller.signal,evaluate}),/abort/i);});
test('complete method extraction and oversized unit refusal',()=>{const text='// filler\n'.repeat(300)+'class Controller {\n handle() { return true; }\n}\n';const unit=excerpt('a.ts',text,302);assert.equal(unit.kind,'complete_syntax_unit');assert.equal(unit.text,'handle() { return true; }');assert.throws(()=>excerpt('a.py','x'.repeat(6000),1),/SOURCE_NEEDS_NARROWER_SCOPE/);});
test('environment variable names are not mistaken for credential values',async t=>{const f=await setup(t);await writeFile(path.join(f.root,'src','paint.ts'),'export const variable = true ? "AI_GATEWAY_API_KEY" : "TYPESAFE_API_KEY";\n');const r=await prepareBrief(f.input,{...f.options,evaluate});assert.equal(r.metrics.calls,1);await writeFile(path.join(f.root,'src','paint.ts'),'const password = "this-is-a-test-secret";\n');await assert.rejects(()=>prepareBrief(f.input,{...f.options,evaluate:()=>assert.fail('No inference')}),/SENSITIVE_SOURCE/);});
test('local variable anchor retains the entire enclosing method',()=>{const text='// filler\n'.repeat(300)+'class Controller {\n handle() {\n const result = 1;\n return result;\n }\n}\n';const unit=excerpt('a.ts',text,303);assert.ok(unit.text.startsWith('handle()'));assert.ok(unit.text.includes('return result;'));});
